### ISSUE TITLE
503 first byte timeout while publishing

### ISSUE THREAD

**Issue by sebastiendavid** [npm/registry-issue-archive#102]
Hi,

I noticed a lot of random 503 failures for several weeks while publishing: sometimes everything is fine, the package is well published, and sometimes it fails because of `503 first byte timeout` error.

As you can see below, npm try to publish the package, it fails with the 503 error, then it retry and fail again because it says that the version of the package is already published: and in fact yes the new version published is available in the registry.

```
info attempt registry request try #1 at 2:33:11 PM
verbose request using bearer token for auth
verbose request id 9d39a6c1c472a7bd
http request PUT https://registry.npmjs.org/@alkem%2ffront-productstream
http 503 https://registry.npmjs.org/@alkem%2ffront-productstream
verbose bad json <?xml version="1.0" encoding="utf-8"?>
verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
verbose bad json <html>
verbose bad json   <head>
verbose bad json     <title>503 first byte timeout</title>
verbose bad json   </head>
verbose bad json   <body>
verbose bad json     <h1>Error 503 first byte timeout</h1>
verbose bad json     <p>first byte timeout</p>
verbose bad json     <h3>Guru Mediation:</h3>
verbose bad json     <p>Details: cache-cdg8720-CDG 1481207607 2191692409</p>
verbose bad json     <hr>
verbose bad json     <p>Varnish cache server</p>
verbose bad json   </body>
verbose bad json </html>
error registry error parsing json
verbose headers { server: 'Varnish',
verbose headers   'retry-after': '0',
verbose headers   'content-type': 'text/html; charset=utf-8',
verbose headers   'content-length': '448',
verbose headers   'accept-ranges': 'bytes',
verbose headers   date: 'Thu, 08 Dec 2016 ',
verbose headers   via: '1.1 varnish',
verbose headers   connection: 'close',
verbose headers   'x-served-by': 'cache-cdg8720-CDG',
verbose headers   'x-cache': 'MISS',
verbose headers   'x-cache-hits': '0',
verbose headers   'x-timer': 'S1481207591.925392,VS0,VE15900' }
info retry will retry, error on last attempt: SyntaxError: Unexpected token < in JSON at position 1
info retry
info retry <?xml version="1.0" encoding="utf-8"?>
info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
info retry <html>
info retry   <head>
info retry     <title>503 first byte timeout</title>
info retry   </head>
info retry   <body>
info retry     <h1>Error 503 first byte timeout</h1>
info retry     <p>first byte timeout</p>
info retry     <h3>Guru Mediation:</h3>
info retry     <p>Details: cache-cdg8720-CDG 1481207607 2191692409</p>
info retry     <hr>
info retry     <p>Varnish cache server</p>
info retry   </body>
info retry </html>
info attempt registry request try #2 at 2:33:37 PM
verbose request using bearer token for auth
http request PUT https://registry.npmjs.org/@alkem%2ffront-productstream
http 403 https://registry.npmjs.org/@alkem%2ffront-productstream
verbose headers { 'content-type': 'application/json',
verbose headers   'cache-control': 'max-age=0',
verbose headers   'content-length': '98',
verbose headers   'accept-ranges': 'bytes',
verbose headers   date: 'Thu, 08 Dec 2016 ',
verbose headers   via: '1.1 varnish',
verbose headers   connection: 'keep-alive',
verbose headers   'x-served-by': 'cache-cdg8734-CDG',
verbose headers   'x-cache': 'MISS',
verbose headers   'x-cache-hits': '0',
verbose headers   'x-timer': 'S1481207618.006320,VS0,VE5873' }
verbose request invalidating /tmp/cache/registry.npmjs.org/_40alkem_252ffront-productstream on PUT
error publish Failed PUT 403
verbose stack Error: "You cannot publish over the previously published version 2.0.53-2." : @alkem/front-productstream
verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:290:14)
verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:187:22)
verbose stack     at emitTwo (events.js:106:13)
verbose stack     at Request.emit (events.js:191:7)
verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1048:10)
verbose stack     at emitOne (events.js:96:13)
verbose stack     at Request.emit (events.js:188:7)
verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:969:12)
verbose statusCode 403
```

Our publish process is automated with Jenkins, and builds are executed in Docker containers. The container use `node@6.9.1` and `npm@3.10.10`.

About timings, here an example of a build failed in Jenkins:

```
14:33:08 + npm publish
14:33:30 npm ERR! registry error parsing json
14:33:45 npm ERR! publish Failed PUT 403
```

It's not really critical since the package seems published anyway, but it's very annoying to have those failures in our build process 😉. So if you can tell me what's wrong with our `npm publish`, I'd like to know 😸.

Of course tell me if you need more information.

**Comment by soldair** [comment]
We'll take a look for anything on our side and maybe extend the first byte timeout for PUTs.

Normally It's that the tarball takes a long time to upload and the publish process after that takes at most a few seconds. In your case, because the client fully sent the tarball and the version was created it could be getting lost somewhere else.

**Comment by sebastiendavid** [comment]
Thanks 👍 I hope you'll find something
