### ISSUE TITLE
Cannot add some packages I own to an org

### ISSUE THREAD

**Issue by lennym** [npm/registry-issue-archive#144]
I recently set up an organisation to manage the vast myriad packages named `hof-*` (https://www.npmjs.com/org/hof)

Trying to run `npm access grant read-write hof:developers [<package>]` works for some packages and fails for others with the following:

```
npm ERR! code E401
npm ERR! user cannot modify package : -/team/hof/developers/package
```

The only common thread I can find that separates packages I can and cannot add to the new org is that packages I can add, I was the last publisher, where if someone else published last then I cannot add the package to the org.

I would expect that I can add any package that I own to an org that I also own.

#### Full npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node@6/6.10.0_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'access',
1 verbose cli   'grant',
1 verbose cli   'read-write',
1 verbose cli   'hof:developers',
1 verbose cli   'hof-form-controller' ]
2 info using npm@4.1.2
3 info using node@v6.10.0
4 silly mapToRegistry name hof-form-controller
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: 'hof-form-controller',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   escapedName: 'hof-form-controller',
7 silly mapToRegistry   name: 'hof-form-controller',
7 silly mapToRegistry   rawSpec: '',
7 silly mapToRegistry   spec: 'latest',
7 silly mapToRegistry   type: 'tag' }
8 silly mapToRegistry uri https://registry.npmjs.org/hof-form-controller
9 verbose request uri https://registry.npmjs.org/-/team/hof/developers/package
10 verbose request sending authorization for write operation
11 info attempt registry request try #1 at 10:47:26 AM
12 verbose request using bearer token for auth
13 verbose request id 697426e4b544285c
14 http request PUT https://registry.npmjs.org/-/team/hof/developers/package
15 http 401 https://registry.npmjs.org/-/team/hof/developers/package
16 verbose headers { 'content-type': 'application/json',
16 verbose headers   'cache-control': 'max-age=300',
16 verbose headers   'content-length': '38',
16 verbose headers   'accept-ranges': 'bytes',
16 verbose headers   date: 'Fri, 24 Mar 2017 10:47:27 GMT',
16 verbose headers   via: '1.1 varnish',
16 verbose headers   connection: 'keep-alive',
16 verbose headers   'x-served-by': 'cache-lcy1134-LCY',
16 verbose headers   'x-cache': 'MISS',
16 verbose headers   'x-cache-hits': '0',
16 verbose headers   'x-timer': 'S1490352446.424157,VS0,VE650',
16 verbose headers   vary: 'Accept-Encoding' }
17 verbose request invalidating /Users/lenny/.npm/registry.npmjs.org/-/team/hof/developers/package on PUT
18 verbose stack Error: user cannot modify package : -/team/hof/developers/package
18 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:12)
18 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:292:14)
18 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:14)
18 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at Request.emit (events.js:191:7)
18 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1081:10)
18 verbose stack     at emitOne (events.js:96:13)
18 verbose stack     at Request.emit (events.js:188:7)
18 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1001:12)
19 verbose statusCode 401
20 verbose cwd /Users/lenny/dev/hof-behaviour-emailer
21 error Darwin 16.4.0
22 error argv "/usr/local/Cellar/node@6/6.10.0_1/bin/node" "/usr/local/bin/npm" "access" "grant" "read-write" "hof:developers" "hof-form-controller"
23 error node v6.10.0
24 error npm  v4.1.2
25 error code E401
26 error user cannot modify package : -/team/hof/developers/package
27 error If you need help, you may report this error at:
27 error     <https://github.com/npm/npm/issues>
28 verbose exit [ 1, true ]
```

**Comment by lennym** [comment]
Actually, having now tried to add more packages it seems I was a little hasty in my assumptions. There seem to be some packages that I was last to publish that still 401 when I try to add them to an org.

There's *something else* that means I can't add packages I own to an org that I also own.

**Comment by ashleygwilliams** [comment]
hi @lennym ! we are currently working to fix this behavior. when we are done with this you should be able to transfer any packages you have write access to. thanks for filing this! i'm going to close, you should see a solution shipped soon!

**Comment by davidrapin** [comment]
@ashleygwilliams I have the exact same issue: I'd like to move package I own to an organization I own. This still does not seems to work, any idea when it will be shipped?

**Comment by lennym** [comment]
Is there any update on this ticket? It's been a month now and I still can't add packages to our org.

Thanks.
