### ISSUE TITLE
Deprecating E400 Issue

### ISSUE THREAD

**Issue by mickit** [npm/registry-issue-archive#155]
hello,

can someone help me with this issue.  i am trying to depreciate a package in my company's private repository and getting this error: 

![deprecationissue](https://cloud.githubusercontent.com/assets/15114234/24663041/a7cf5364-190b-11e7-91c5-67d5fbddf928.jpg)

debug.log:

```text
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'deprecate',
1 verbose cli   'ash-odi@<0.1.5',
1 verbose cli   'WARNING: This module has been renamed to ash-assessment. Please install it instead.' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 silly mapToRegistry name ash-odi
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry http://23.21.19.115:4873/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: 'ash-odi',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   escapedName: 'ash-odi',
7 silly mapToRegistry   name: 'ash-odi',
7 silly mapToRegistry   rawSpec: '',
7 silly mapToRegistry   spec: 'latest',
7 silly mapToRegistry   type: 'tag' }
8 silly mapToRegistry uri http://23.21.19.115:4873/ash-odi
9 verbose get GET as part of write; not caching result
10 verbose request uri http://23.21.19.115:4873/ash-odi?write=true
11 verbose request no auth needed
12 info attempt registry request try #1 at 7:46:50 AM
13 verbose request using bearer token for auth
14 verbose request id 960148ffa02d7dc2
15 http request GET http://23.21.19.115:4873/ash-odi?write=true
16 http 200 http://23.21.19.115:4873/ash-odi?write=true
17 verbose headers { 'x-powered-by': 'Sinopia/1.4.0',
17 verbose headers   'content-type': 'application/json; charset=utf-8',
17 verbose headers   etag: '"8a09d7b748523b703b81022d0b9b0a6d"',
17 verbose headers   vary: 'Accept-Encoding',
17 verbose headers   'content-encoding': 'gzip',
17 verbose headers   'x-status-cat': 'http://flic.kr/p/aVuVsF',
17 verbose headers   date: 'Tue, 04 Apr 2017 14:46:50 GMT',
17 verbose headers   connection: 'keep-alive',
17 verbose headers   'transfer-encoding': 'chunked' }
18 silly get cb [ 200,
18 silly get   { 'x-powered-by': 'Sinopia/1.4.0',
18 silly get     'content-type': 'application/json; charset=utf-8',
18 silly get     etag: '"8a09d7b748523b703b81022d0b9b0a6d"',
18 silly get     vary: 'Accept-Encoding',
18 silly get     'content-encoding': 'gzip',
18 silly get     'x-status-cat': 'http://flic.kr/p/aVuVsF',
18 silly get     date: 'Tue, 04 Apr 2017 14:46:50 GMT',
18 silly get     connection: 'keep-alive',
18 silly get     'transfer-encoding': 'chunked' } ]
19 verbose get saving ash-odi to C:\Users\mickit\AppData\Roaming\npm-cache\23.21.19.115_4873\ash-odi_3Fwrite_3Dtrue\.cache.json
20 verbose correctMkdir C:\Users\mickit\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
21 verbose request uri http://23.21.19.115:4873/ash-odi
22 verbose request sending authorization for write operation
23 info attempt registry request try #1 at 7:46:50 AM
24 verbose request using bearer token for auth
25 http request PUT http://23.21.19.115:4873/ash-odi
26 http 400 http://23.21.19.115:4873/ash-odi
27 verbose headers { 'x-powered-by': 'Sinopia/1.4.0',
27 verbose headers   'content-type': 'application/json; charset=utf-8',
27 verbose headers   'content-length': '43',
27 verbose headers   vary: 'Accept-Encoding',
27 verbose headers   'x-status-cat': 'http://flic.kr/p/aXYDeT',
27 verbose headers   date: 'Tue, 04 Apr 2017 14:46:50 GMT',
27 verbose headers   connection: 'keep-alive' }
28 verbose request invalidating C:\Users\mickit\AppData\Roaming\npm-cache\23.21.19.115_4873\ash-odi on PUT
29 verbose stack Error: unsupported registry call : ash-odi
29 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
29 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:290:14)
29 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
29 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
29 verbose stack     at emitTwo (events.js:106:13)
29 verbose stack     at Request.emit (events.js:191:7)
29 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
29 verbose stack     at emitOne (events.js:96:13)
29 verbose stack     at Request.emit (events.js:188:7)
29 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
30 verbose statusCode 400
31 verbose pkgid ash-odi
32 verbose cwd C:\Projects\ASH-TFS12\WD\UI\Web\Main\Web\repo\npm\ember\addon
33 error Windows_NT 6.1.7601
34 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "deprecate" "ash-odi@<0.1.5" "WARNING: This module has been renamed to ash-assessment. Please install it instead."
35 error node v6.10.0
36 error npm  v3.10.10
37 error code E400
38 error unsupported registry call : ash-odi
39 error If you need help, you may report this error at:
39 error     <https://github.com/npm/npm/issues>
40 verbose exit [ 1, true ]
```

thanks in advance for your help.

**Comment by bcoe** [comment]
@mickit hey, it looks like your company is using Sinopia for its private registry which isn't 100% feature compatible with the npm Registry. A list of the differences can be found here:

https://github.com/rlidwka/sinopia#compatibility

Sinopia is open-source, so you could potentially chip in and help add these features.

npm Also has its own Enterprise version of the registry, which uses the same codebase as the public registry and supports features such as deprecation; a free trial is available here:

https://www.npmjs.com/enterprise
