### ISSUE TITLE
Cannot publish a package I own - returns 403

### ISSUE THREAD

**Issue by lennym** [npm/registry-issue-archive#157]
I am an owner on the module [hof-govuk-template](https://www.npmjs.com/package/hof-govuk-template).

When I try to publish said module I get a 403 with the following logs:

<details>

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node@6/6.9.4/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@4.5.0
3 info using node@v6.9.4
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   escapedName: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/lenny/dev/hof/hof-govuk-template',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/lenny/.npm/hof-govuk-template/2.0.0/package.tgz not in flight; packing
9 verbose correctMkdir /Users/lenny/.npm correctMkdir not in flight; initializing
10 warn prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
11 warn prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
12 warn prepublish-on-install See the deprecation note in `npm help scripts` for more information.
13 info lifecycle hof-govuk-template@2.0.0~prepublish: hof-govuk-template@2.0.0
14 verbose lifecycle hof-govuk-template@2.0.0~prepublish: unsafe-perm in lifecycle true
15 verbose lifecycle hof-govuk-template@2.0.0~prepublish: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/lenny/dev/hof/hof-govuk-template/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/share/npm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/MacGPG2/bin
16 verbose lifecycle hof-govuk-template@2.0.0~prepublish: CWD: /Users/lenny/dev/hof/hof-govuk-template
17 silly lifecycle hof-govuk-template@2.0.0~prepublish: Args: [ '-c', 'node ./build/index.js' ]
18 silly lifecycle hof-govuk-template@2.0.0~prepublish: Returned: code: 0  signal: null
19 info lifecycle hof-govuk-template@2.0.0~prepare: hof-govuk-template@2.0.0
20 silly lifecycle hof-govuk-template@2.0.0~prepare: no script for prepare, continuing
21 verbose tar pack [ '/Users/lenny/.npm/hof-govuk-template/2.0.0/package.tgz',
21 verbose tar pack   '/Users/lenny/dev/hof/hof-govuk-template' ]
22 verbose tarball /Users/lenny/.npm/hof-govuk-template/2.0.0/package.tgz
23 verbose folder /Users/lenny/dev/hof/hof-govuk-template
24 verbose addLocalTarball adding from inside cache /Users/lenny/.npm/hof-govuk-template/2.0.0/package.tgz
25 verbose correctMkdir /Users/lenny/.npm correctMkdir not in flight; initializing
26 silly cache afterAdd hof-govuk-template@2.0.0
27 verbose afterAdd /Users/lenny/.npm/hof-govuk-template/2.0.0/package/package.json not in flight; writing
28 verbose correctMkdir /Users/lenny/.npm correctMkdir not in flight; initializing
29 verbose afterAdd /Users/lenny/.npm/hof-govuk-template/2.0.0/package/package.json written
30 silly publish { name: 'hof-govuk-template',
30 silly publish   version: '2.0.0',
30 silly publish   description: 'Compile govuk mustache template into a more usable format and provide middleware for use in apps',
30 silly publish   scripts:
30 silly publish    { lint: 'eslint .',
30 silly publish      test: 'npm run lint',
30 silly publish      prepublish: 'node ./build/index.js' },
30 silly publish   main: 'index.js',
30 silly publish   repository:
30 silly publish    { type: 'git',
30 silly publish      url: 'git+https://github.com/UKHomeOfficeForms/hof-govuk-template.git' },
30 silly publish   author: '',
30 silly publish   license: 'MIT',
30 silly publish   bugs: { url: 'https://github.com/UKHomeOfficeForms/hof-govuk-template/issues' },
30 silly publish   homepage: 'https://github.com/UKHomeOfficeForms/hof-govuk-template',
30 silly publish   dependencies:
30 silly publish    { express: '^4.15.2',
30 silly publish      govuk_template_mustache: '^0.17.3',
30 silly publish      'serve-static': '^1.10.3' },
30 silly publish   devDependencies:
30 silly publish    { eslint: '^3.19.0',
30 silly publish      'eslint-config-homeoffice': '^2.1.2',
30 silly publish      'hogan.js': '3.0.2' },
30 silly publish   readme: '# hof-govuk-template\n\nCompiles govuk mustache template into a more usable format and provide middleware for use in apps.\n\nExisting [govuk mustache template](https://www.npmjs.com/package/govuk_template_mustache) has simple mustache placeholders for content sections, which necessitates a two step compile process where sections are compiled individually and then again into the parent template.\n\nCompiling the template to replace these placeholders with variables allows for templates to implement the govuk template as a parent partial.\n\n## Example\n\n```\n{{< govuk-template}}\n\n    {{$main}}\n        <h1>Page Content</h1>\n    {{/main}}\n\n{{/ govuk-template}}\n```\n\n## Installation\n\n```\nnpm install [--save] hof-govuk-template\n```\n\n## Usage\n\nWhen used as part of an express app, a middleware is returned which will add a static fileserver (using [serve-static](https://www.npmjs.com/package/serve-static)) to serve the template assets without needing to copy them to any other location.\n\nIt will also add the template as a mustache partial with a name of "govuk-template".\n\n### To configure express middleware\n```\napp.use(require(\'hof-govuk-template\')([options]);\n```\n\n### To use the mustache partial\n```\n{{< govuk-template}}\n    {{$pageTitle}}An example page{{/pageTitle}}\n    {{$main}}\n        <h1>Page Content</h1>\n    {{/main}}\n{{/ govuk-template}}\n```\n\n## Options\n\nA number of options can be passed with the app into the setup method:\n\n* `path` - Sets the base path for the location of static assets - Default: `/govuk-assets`\n\nOther options are passed onto the [serve-static](https://www.npmjs.com/package/serve-static) configuration, and more details can be found in [the serve-static documentation](https://www.npmjs.com/package/serve-static)\n\n## Example\n\nThere is an example implmentation in \'/example\'. To run:\n\n```\ncd example\nnpm install\nnpm start\n```',
30 silly publish   readmeFilename: 'README.md',
30 silly publish   gitHead: 'e08fe8c5537c43bdb0a461ca47f287b24dc06d8c',
30 silly publish   _id: 'hof-govuk-template@2.0.0',
30 silly publish   _shasum: 'a724759c600f3540cdaea19e95205ddbd5270dad',
30 silly publish   _from: '.' }
31 info lifecycle hof-govuk-template@2.0.0~prepublishOnly: hof-govuk-template@2.0.0
32 silly lifecycle hof-govuk-template@2.0.0~prepublishOnly: no script for prepublishOnly, continuing
33 verbose getPublishConfig undefined
34 silly mapToRegistry name hof-govuk-template
35 silly mapToRegistry using default registry
36 silly mapToRegistry registry https://registry.npmjs.org/
37 silly mapToRegistry data Result {
37 silly mapToRegistry   raw: 'hof-govuk-template',
37 silly mapToRegistry   scope: null,
37 silly mapToRegistry   escapedName: 'hof-govuk-template',
37 silly mapToRegistry   name: 'hof-govuk-template',
37 silly mapToRegistry   rawSpec: '',
37 silly mapToRegistry   spec: 'latest',
37 silly mapToRegistry   type: 'tag' }
38 silly mapToRegistry uri https://registry.npmjs.org/hof-govuk-template
39 verbose publish registryBase https://registry.npmjs.org/
40 silly publish uploading /Users/lenny/.npm/hof-govuk-template/2.0.0/package.tgz
41 verbose request uri https://registry.npmjs.org/hof-govuk-template
42 verbose request sending authorization for write operation
43 info attempt registry request try #1 at 3:12:40 PM
44 verbose request using bearer token for auth
45 verbose request id e3f12d8104e44df6
46 http request PUT https://registry.npmjs.org/hof-govuk-template
47 http 403 https://registry.npmjs.org/hof-govuk-template
48 verbose headers { 'content-type': 'application/json',
48 verbose headers   'cache-control': 'max-age=300',
48 verbose headers   'content-length': '112',
48 verbose headers   'accept-ranges': 'bytes',
48 verbose headers   date: 'Wed, 19 Apr 2017 14:12:40 GMT',
48 verbose headers   via: '1.1 varnish',
48 verbose headers   connection: 'keep-alive',
48 verbose headers   'x-served-by': 'cache-cdg8732-CDG',
48 verbose headers   'x-cache': 'MISS',
48 verbose headers   'x-cache-hits': '0',
48 verbose headers   'x-timer': 'S1492611160.946554,VS0,VE592',
48 verbose headers   vary: 'Accept-Encoding' }
49 verbose request invalidating /Users/lenny/.npm/registry.npmjs.org/hof-govuk-template on PUT
50 error publish Failed PUT 403
51 verbose stack Error: you do not have permission to publish "hof-govuk-template". Are you logged in as the correct user? : hof-govuk-template
51 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:12)
51 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:296:14)
51 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
51 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:188:22)
51 verbose stack     at emitTwo (events.js:106:13)
51 verbose stack     at Request.emit (events.js:191:7)
51 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1171:10)
51 verbose stack     at emitOne (events.js:96:13)
51 verbose stack     at Request.emit (events.js:188:7)
51 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1091:12)
52 verbose statusCode 403
53 verbose pkgid hof-govuk-template
54 verbose cwd /Users/lenny/dev/hof/hof-govuk-template
55 verbose Darwin 16.5.0
56 verbose argv "/usr/local/Cellar/node@6/6.9.4/bin/node" "/usr/local/bin/npm" "publish"
57 verbose node v6.9.4
58 verbose npm  v4.5.0
59 error code E403
60 error you do not have permission to publish "hof-govuk-template". Are you logged in as the correct user? : hof-govuk-template
61 verbose exit [ 1, true ]
```

</details>

### Possibly relevant information:

I have only *just* been added as an owner (approx 10 minutes ago), and my colleague reported that they could not add me via the command line and had to do it manually through the website.

**Comment by lennym** [comment]
It seems that this has resolved itself though waiting a bit. Closing.
