### ISSUE TITLE
After upgrading to Node 8.2.1 and npm 5.3.0 any dependencies starting with `@` fail with 404

### ISSUE THREAD

**Issue by randyaa** [npm/registry-issue-archive#195]
After upgrading to Node 8.2.1 and npm 5.3.0 any dependencies starting with `@` fail withn http 404 return code

I've tried

- clearing local caches, 
- different consoles, 
- comparing config settings to people that dont have problems
- changing the repository to http instead of https
- checking the hosts file for strange redirects
- adding the redirects listed at the bottom of https://github.com/npm/npm/issues/13289
- different networks (both internal to the company but one wifi one wired. I didn't verify different hops but i'm pretty sure they are)
- checking the npm repo status - https://status.npmjs.org/
- recloning my repository (not really sure why, just something i tried)
- uninstall nodejs, re-install nodejs (still 8.2.1)

EVERYTHING seems to yield the same result.

The easiest way to reproduce this problem I've seen is start with a blank repository and just run `npm i "@angular/core"`

which yields the following for me:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '@angular/core' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose npm-session e05a769a72d84ace
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@angular%2fcore 945ms
8 silly fetchPackageMetaData error for @angular/core@4.3.1 404 Not Found: @angular/core@4.3.1
9 verbose stack Error: 404 Not Found: @angular/core@4.3.1
9 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:41:19)
9 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:781:20)
9 verbose stack     at tryOnImmediate (timers.js:743:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
10 verbose cwd C:\extras\code\gitlab\projectx\authoring-ui
11 verbose Windows_NT 6.1.7601
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "@angular/core"
13 verbose node v8.2.1
14 verbose npm  v5.3.0
15 error code E404
16 error 404 Not Found: @angular/core@4.3.1
17 verbose exit [ 1, true ]
```

Installing something without the @ like `npm i typescript` works just fine.

**Comment by soldair** [comment]
because this is a cli issue and you have a cli issue open with the same details I'm going to close this.
if this is and error please let me know.
