### ISSUE TITLE
Mithril v1.1.6 has been released but can't be installed

### ISSUE THREAD

**Issue by pygy** [npm/registry-issue-archive#249]
Hello, I've released Mithril v1.1.6 a few days ago, and while the [main NPM web](https://www.npmjs.com/package/mithril) site 
 and at least one [CDN](https://unpkg.com/mithril) have picked it up, it can't be installed from the CLI using either the NPM client (v5.5.1) or Yarn (v1.3.2). 

`npm i mithril` fetches v1.1.5, and `npm i mithril@1.1.6` fails with the following log:

Highlight:

```text
7 http fetch GET 200 https://registry.npmjs.org/mithril 19ms (from cache)
8 silly registry:manifest no matching version for mithril@1.1.6 in the cache. Forcing revalidation
9 http fetch GET 304 https://registry.npmjs.org/mithril 219ms (from cache)
10 silly fetchPackageMetaData error for mithril@1.1.6 No matching version found for mithril@1.1.6
```

Full log

```text
~/tmp ❯❯❯ cat /Users/pygy/.npm/_logs/2017-12-05T13_00_24_921Z-debug.log                                                                                                                            ⏎
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.9.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   'mithril@1.1.6' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose npm-session 9932eb8b78297c3e
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/mithril 19ms (from cache)
8 silly registry:manifest no matching version for mithril@1.1.6 in the cache. Forcing revalidation
9 http fetch GET 304 https://registry.npmjs.org/mithril 219ms (from cache)
10 silly fetchPackageMetaData error for mithril@1.1.6 No matching version found for mithril@1.1.6
11 verbose type version
12 verbose stack mithril: No matching version found for mithril@1.1.6
12 verbose stack     at pickManifest (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/npm-pick-manifest/index.js:61:11)
12 verbose stack     at fetchPackument.then.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:51:18)
12 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
12 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
12 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
12 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
12 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
12 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
12 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
12 verbose stack     at runCallback (timers.js:789:20)
12 verbose stack     at tryOnImmediate (timers.js:751:5)
12 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
13 verbose cwd /Users/pygy/tmp
14 verbose Darwin 16.7.0
15 verbose argv "/usr/local/Cellar/node/8.9.1/bin/node" "/usr/local/bin/npm" "i" "mithril@1.1.6"
16 verbose node v8.9.1
17 verbose npm  v5.5.1
18 error code ETARGET
19 error notarget No matching version found for mithril@1.1.6
20 error notarget In most cases you or one of your dependencies are requesting
20 error notarget a package version that doesn't exist.
21 verbose exit [ 1, true ]
```

**Comment by pygy** [comment]
We release from Travis, I hadn't checked the log:

```
Preparing deploy
NPM version: 5.5.1
Authenticated with email npm@patcavit.com
NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.
http://docs.travis-ci.com/user/deployment/npm/
~/.npmrc size: 48
```

Could it be the culprit?
cc @tivac

**Comment by soldair** [comment]
I'll take a look at this now. Thanks for reporting!

**Comment by soldair** [comment]
looks like 1.1.6 is available now and should work great.
we made some backend changes yesterday and a handful of stale documents caused issues but have been fixed. please let me know if you run into this again.

**Comment by pygy** [comment]
@soldair thanks for looking into it.

I still can't install v1.1.6 from my laptop (), could there be a stale cache somewhere between the registry and my machine?

**Comment by soldair** [comment]
I found the stale cached item. Looks like the minified version of the packument that npm > 5 uses failed to update. i ran `npm star mithril` to force a change and it was picked up, updated, and purged from cache. Ill take a look into the system and hunt down the root cause. 

thanks again for the report! please let me know if its working for you now.

**Comment by pygy** [comment]
It works now, thanks for the quick fix!
