### ISSUE TITLE
Received a 503 from couch

### ISSUE THREAD

**Issue by zeke** [npm/registry-issue-archive#264]
Very near the end of a feed from replicate.npmjs.com, I got this error which I've never seen before:

```
⠧ 602836

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Received a 503 from couch
    at ChangesStream._onResponse (/app/node_modules/changes-stream/index.js:155:15)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! all-the-package-repos@1.4.1 build: `node scripts/build.js`
```

Versions:

```
$ npm ls changes-stream
all-the-package-repos@1.4.1 /Users/z/git/nice-registry/all-the-package-repos
└─┬ package-stream@3.0.1
  └── changes-stream@1.1.0 
```

**Comment by zeke** [comment]
When running that process again, I got another error I don't often see:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: CouchDB disconnected gracefully
    at ChangesStream._onEnd (/app/node_modules/changes-stream/index.js:272:17)
```

**Comment by soldair** [comment]
Interesting. This last one happens when couch restarts.  We handle this by binding error and changes-stream reconnects itself

**Comment by zeke** [comment]
> We handle this by binding error and changes-stream reconnects itself

I see, thanks. Can you share a code snippet of this technique?

**Comment by encron** [comment]
@zeke So did you get this fixed after all? Running into the same error here...

**Comment by zeke** [comment]
I haven't seen this with my own eyes lately, but I think it may still be happening.

I have a process that runs once a day attempting to collect all the package repository URLs in the registry.[1] It runs once a day, but you can see from the commit history that it doesn't actually succeed every day. The days that it fails (at least last time I was watching closely) are the days when the above error occurs. I know that's unscientific but it's what I remember. Hope that helps!

1. https://github.com/nice-registry/all-the-package-repos/commits/master
