### ISSUE TITLE
No valid versions available for express-request-id (NPM v5.5.1)

### ISSUE THREAD

**Issue by chambois** [npm/registry-issue-archive#265]
Hey folks,

We're experiencing problems trying to `npm install` with it saying there's `No valid versions available for express-request-id`.

**Node version**: 9.3.0
**NPM version**: 5.5.1

**Error message**:
```
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for express-request-id

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mchamber/.npm/_logs/2018-01-11T01_21_14_935Z-debug.log
```

**Debug log**:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/nvm/0.33.1/versions/node/v9.3.0/bin/node',
1 verbose cli   '/usr/local/opt/nvm/versions/node/v9.3.0/bin/npm',
1 verbose cli   'i' ]
2 info using npm@5.5.1
3 info using node@v9.3.0
4 verbose npm-session 3a324b53dde03372
5 silly install runPreinstallTopLevelLifecycles
6 [redacted]
7 [redacted]
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 warn read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 silly install loadShrinkwrap

...

449 http fetch GET 200 https://registry.npmjs.org/express-request-id 81ms
450 silly fetchPackageMetaData error for express-request-id@1.4.0 No valid versions available for express-request-id
451 verbose type version
452 verbose stack express-request-id: No valid versions available for express-request-id
452 verbose stack     at pickManifest (/usr/local/Cellar/nvm/0.33.1/versions/node/v9.3.0/lib/node_modules/npm/node_modules/pacote/node_modules/npm-pick-manifest/index.js:19:11)
452 verbose stack     at fetchPackument.then.packument (/usr/local/Cellar/nvm/0.33.1/versions/node/v9.3.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:39:14)
452 verbose stack     at tryCatcher (/usr/local/Cellar/nvm/0.33.1/versions/node/v9.3.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
452 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/Cellar/nvm/0.33.1/versions/node/v9.3.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
452 verbose stack     at Promise._settlePromise (/usr/local/Cellar/nvm/0.33.1/versions/node/v9.3.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
452 verbose stack     at Promise._settlePromise0 (/usr/local/Cellar/nvm/0.33.1/versions/node/v9.3.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
452 verbose stack     at Promise._settlePromises (/usr/local/Cellar/nvm/0.33.1/versions/node/v9.3.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
452 verbose stack     at Async._drainQueue (/usr/local/Cellar/nvm/0.33.1/versions/node/v9.3.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
452 verbose stack     at Async._drainQueues (/usr/local/Cellar/nvm/0.33.1/versions/node/v9.3.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
452 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/Cellar/nvm/0.33.1/versions/node/v9.3.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
452 verbose stack     at runCallback (timers.js:773:18)
452 verbose stack     at tryOnImmediate (timers.js:734:5)
452 verbose stack     at processImmediate [as _immediateCallback] (timers.js:711:5)
453 [redacted]
454 verbose Darwin 16.7.0
455 verbose argv "/usr/local/Cellar/nvm/0.33.1/versions/node/v9.3.0/bin/node" "/usr/local/opt/nvm/versions/node/v9.3.0/bin/npm" "i"
456 verbose node v9.3.0
457 verbose npm  v5.5.1
458 error code ENOVERSIONS
459 error No valid versions available for express-request-id
460 verbose exit [ 1, true ]
```

Is it related to #255 ?

**Comment by soldair** [comment]
it may have been. looks like its resolved now.
if you're in Australia we had a short time where we turned on a lower latency backend we prepared before the incident that didn't have fix. we rolled the change back.

**Comment by chambois** [comment]
Thanks @soldair for your help! :)
