### ISSUE TITLE
Package entitled 'package' : No valid versions available for package

### ISSUE THREAD

**Issue by stephen-standridge** [npm/registry-issue-archive#275]
Installing this from [temporary](https://github.com/vesln/temporary), which expects this package to retrieve the `package.json` from the module. It appears as though a package called [package](https://www.npmjs.com/package/Package) exists, but maybe it's not the package that is expected by the repo. This affects many other packages like `grunt-mocha` and `grunt-controb-phantomjs`.

Here's the error log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/npm/dir/.nvm/versions/node/v9.3.0/bin/node',
1 verbose cli   '/npm/dir/.nvm/versions/node/v9.3.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   'package' ]
2 info using npm@5.6.0
3 info using node@v9.3.0
4 verbose npm-session de1fd36eda1a1455
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/package 241ms (from cache)
8 silly fetchPackageMetaData error for package@latest No valid versions available for package
9 verbose type tag
10 verbose stack package: No valid versions available for package
10 verbose stack     at pickManifest (/npm/dir/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/pacote/node_modules/npm-pick-manifest/index.js:20:11)
10 verbose stack     at fetchPackument.then.packument (/npm/dir/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:39:14)
10 verbose stack     at tryCatcher (/npm/dir/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
10 verbose stack     at Promise._settlePromiseFromHandler (/npm/dir/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
10 verbose stack     at Promise._settlePromise (/npm/dir/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
10 verbose stack     at Promise._settlePromise0 (/npm/dir/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
10 verbose stack     at Promise._settlePromises (/npm/dir/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
10 verbose stack     at Async._drainQueue (/npm/dir/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
10 verbose stack     at Async._drainQueues (/npm/dir/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
10 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/npm/dir/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
10 verbose stack     at runCallback (timers.js:773:18)
10 verbose stack     at tryOnImmediate (timers.js:734:5)
10 verbose stack     at processImmediate [as _immediateCallback] (timers.js:711:5)
11 verbose cwd /npm/dir/workspace/temporary
12 verbose Darwin 17.2.0
13 verbose argv "/npm/dir/.nvm/versions/node/v9.3.0/bin/node" "/npm/dir/.nvm/versions/node/v9.3.0/bin/npm" "install" "package"
14 verbose node v9.3.0
15 verbose npm  v5.6.0
16 error code ENOVERSIONS
17 error No valid versions available for package
18 verbose exit [ 1, true ]
```

I've also tested this on other machines and seem to have the same issue. Plaese... halp?

**Comment by ashleygwilliams** [comment]
hello @stephen-standridge ! we have an incident open for this and are currently working to restore this and 2 other packages right now. you can view the status here: https://status.npmjs.org/. and follow [@npmstatus](https://twitter.com/npmstatus) for updates.

**Comment by ashleygwilliams** [comment]
hi @stephen-standridge ! the status incident has been resolved and all packages have been restored. i will be closing this issue but please feel free to reopen if you continue to have trouble. thanks for your patience and understanding!
