### ISSUE TITLE
500 error on `npm publish` for a new package

### ISSUE THREAD

**Issue by mathieujonson** [npm/registry-issue-archive#280]
I'm attempting to create a new package, but I'm getting a 500 error when I try `npm publish`.

## Error from the command line

```
$ npm publish
npm ERR! publish Failed PUT 500
npm ERR! code E500
npm ERR! Unexpected error (488b1f4d-b9ea-49bf-af0b-9ac04a9ae28d). : hack-pack

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/matt/.npm/_logs/2018-02-19T01_10_34_123Z-debug.log
```

## Error from the log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session 8d5febd91380a293
5 verbose publish [ '.' ]
6 info lifecycle hack-pack@0.1.0~prepublish: hack-pack@0.1.0
7 info lifecycle hack-pack@0.1.0~prepare: hack-pack@0.1.0
8 info lifecycle hack-pack@0.1.0~prepublishOnly: hack-pack@0.1.0
9 info lifecycle hack-pack@0.1.0~prepack: hack-pack@0.1.0
10 info lifecycle hack-pack@0.1.0~postpack: hack-pack@0.1.0
11 verbose getPublishConfig undefined
12 silly mapToRegistry name hack-pack
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data { type: 'tag',
15 silly mapToRegistry   registry: true,
15 silly mapToRegistry   where: undefined,
15 silly mapToRegistry   raw: 'hack-pack',
15 silly mapToRegistry   name: 'hack-pack',
15 silly mapToRegistry   escapedName: 'hack-pack',
15 silly mapToRegistry   scope: undefined,
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   saveSpec: null,
15 silly mapToRegistry   fetchSpec: 'latest',
15 silly mapToRegistry   gitRange: undefined,
15 silly mapToRegistry   gitCommittish: undefined,
15 silly mapToRegistry   hosted: undefined }
16 silly mapToRegistry uri https://registry.npmjs.org/hack-pack
17 verbose publish registryBase https://registry.npmjs.org/
18 silly publish uploading /var/folders/1b/z6zw5pjx7q90vq80wz5t5p2r0000gp/T/npm-20245-022eec9c/tmp/fromDir-d8db6160/package.tgz
19 verbose request uri https://registry.npmjs.org/hack-pack
20 verbose request sending authorization for write operation
21 info attempt registry request try #1 at 19:09:20
22 verbose request using bearer token for auth
23 verbose request id 18e32befdf5d8b94
24 http request PUT https://registry.npmjs.org/hack-pack
25 http 500 https://registry.npmjs.org/hack-pack
26 verbose headers { 'content-type': 'application/json',
26 verbose headers   'cache-control': 'max-age=0',
26 verbose headers   'content-length': '68',
26 verbose headers   'accept-ranges': 'bytes',
26 verbose headers   date: 'Mon, 19 Feb 2018 01:09:16 GMT',
26 verbose headers   via: '1.1 varnish',
26 verbose headers   connection: 'keep-alive',
26 verbose headers   'x-served-by': 'cache-mdw17334-MDW',
26 verbose headers   'x-cache': 'MISS',
26 verbose headers   'x-cache-hits': '0',
26 verbose headers   'x-timer': 'S1519002556.667003,VS0,VE860' }
27 info retry will retry, error on last attempt: Error: Unexpected error (2ce01e86-ab88-4ae0-a371-74127ac64cf0). : hack-pack
28 info attempt registry request try #2 at 19:09:32
29 verbose request using bearer token for auth
30 http request PUT https://registry.npmjs.org/hack-pack
31 http 500 https://registry.npmjs.org/hack-pack
32 verbose headers { 'content-type': 'application/json',
32 verbose headers   'cache-control': 'max-age=0',
32 verbose headers   'content-length': '68',
32 verbose headers   'accept-ranges': 'bytes',
32 verbose headers   date: 'Mon, 19 Feb 2018 01:09:27 GMT',
32 verbose headers   via: '1.1 varnish',
32 verbose headers   connection: 'keep-alive',
32 verbose headers   'x-served-by': 'cache-mdw17334-MDW',
32 verbose headers   'x-cache': 'MISS',
32 verbose headers   'x-cache-hits': '0',
32 verbose headers   'x-timer': 'S1519002567.859594,VS0,VE804' }
33 info retry will retry, error on last attempt: Error: Unexpected error (ec016d75-9b8a-4233-b302-5b3e20a7aaf4). : hack-pack
34 info attempt registry request try #3 at 19:10:33
35 verbose request using bearer token for auth
36 http request PUT https://registry.npmjs.org/hack-pack
37 http 500 https://registry.npmjs.org/hack-pack
38 verbose headers { 'content-type': 'application/json',
38 verbose headers   'cache-control': 'max-age=0',
38 verbose headers   'content-length': '68',
38 verbose headers   'accept-ranges': 'bytes',
38 verbose headers   date: 'Mon, 19 Feb 2018 01:10:28 GMT',
38 verbose headers   via: '1.1 varnish',
38 verbose headers   connection: 'keep-alive',
38 verbose headers   'x-served-by': 'cache-mdw17334-MDW',
38 verbose headers   'x-cache': 'MISS',
38 verbose headers   'x-cache-hits': '0',
38 verbose headers   'x-timer': 'S1519002628.910575,VS0,VE823' }
39 error publish Failed PUT 500
40 verbose stack Error: Unexpected error (488b1f4d-b9ea-49bf-af0b-9ac04a9ae28d). : hack-pack
40 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:314:12)
40 verbose stack     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:14)
40 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
40 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
40 verbose stack     at emitTwo (events.js:126:13)
40 verbose stack     at Request.emit (events.js:214:7)
40 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1163:10)
40 verbose stack     at emitOne (events.js:116:13)
40 verbose stack     at Request.emit (events.js:211:7)
40 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1085:12)
40 verbose stack     at Object.onceWrapper (events.js:313:30)
40 verbose stack     at emitNone (events.js:111:20)
40 verbose stack     at IncomingMessage.emit (events.js:208:7)
40 verbose stack     at endReadableNT (_stream_readable.js:1055:12)
40 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
40 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
41 verbose statusCode 500
42 verbose pkgid hack-pack
43 verbose cwd /Users/matt/Sites/hack-pack
44 verbose Darwin 15.6.0
45 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
46 verbose node v8.9.4
47 verbose npm  v5.6.0
48 error code E500
49 error Unexpected error (488b1f4d-b9ea-49bf-af0b-9ac04a9ae28d). : hack-pack
50 verbose exit [ 1, true ]
```

## `package.json`:

```
{
  "name": "hack-pack",
  "version": "0.1.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/mathieujonson/hack-pack.git"
  },
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-redux": "^5.0.6",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.1.1",
    "redux": "^3.7.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "jest": "20.0.4"
  },
  "description": "React app for Hackathons",
  "bugs": {
    "url": "https://github.com/mathieujonson/hack-pack/issues"
  },
  "homepage": "https://github.com/mathieujonson/hack-pack#readme",
  "main": "./src/index.js",
  "keywords": [
    "react"
  ],
  "author": "Matthew Johnson",
  "license": "MIT"
}
```

## Currently running:
`node -v`: v8.9.4
`npm -v`: 5.6.0

## Attempted

I've run `npm login`, and the `npm whoami` returns my correct user name.  I've also tried with the `main` in `package.json` set to just `index.js`.  I've also tried starting from scratch with `npm init`, and immediately running `npm publish`, still no luck.  It seems I just can't publish to NPM.

**Comment by aearly** [comment]
You're probably getting caught in the spam filter due to the name of the module. Contact npm support and they will sort it out for you!

**Comment by mathieujonson** [comment]
Thank you!  I actually just submitted from their contact form.  I'll try renaming the package and see how that goes.

**Comment by mathieujonson** [comment]
@aearly Wow, so that was it.  I renamed to `hackathon-pack` and it sailed through.  Hours banging my head against the wall, and such a simple fix.  Thanks!

**Comment by mathieujonson** [comment]
As a side note, it would be awesome to have the details of the fail listed in the response.

**Comment by aearly** [comment]
We have to be vague about the details, otherwise we give spammers a map through the spam filter.
