### ISSUE TITLE
Grant access to team forbidden

### ISSUE THREAD

**Issue by jorgebay** [npm/registry-issue-archive#281]
I'm trying to grant package access to a team for which I'm one of the owners:

- Package: gremlin
- My username: jorgebay

And I'm getting a 403 response from the server.

The other owner of the package is also unable to grant access.

I'm able to grant access for other packages to the same team.

I think it may be related to the fact that we are not the original maintainers of the package.

These are the cli log messages, when I execute `npm access grant read-write tinkerpop:developers gremlin`

```
1 verbose cli [ '/Users/jorge/.nvm/versions/node/v8.9.3/bin/node',
1 verbose cli   '/Users/jorge/.nvm/versions/node/v8.9.3/bin/npm',
1 verbose cli   'access',
1 verbose cli   'grant',
1 verbose cli   'read-write',
1 verbose cli   'tinkerpop:developers',
1 verbose cli   'gremlin' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 silly mapToRegistry name gremlin
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry data { type: 'tag',
7 silly mapToRegistry   registry: true,
7 silly mapToRegistry   where: undefined,
7 silly mapToRegistry   raw: 'gremlin',
7 silly mapToRegistry   name: 'gremlin',
7 silly mapToRegistry   escapedName: 'gremlin',
7 silly mapToRegistry   scope: undefined,
7 silly mapToRegistry   rawSpec: '',
7 silly mapToRegistry   saveSpec: null,
7 silly mapToRegistry   fetchSpec: 'latest',
7 silly mapToRegistry   gitRange: undefined,
7 silly mapToRegistry   gitCommittish: undefined,
7 silly mapToRegistry   hosted: undefined }
8 silly mapToRegistry uri https://registry.npmjs.org/gremlin
9 verbose request uri https://registry.npmjs.org/-/team/tinkerpop/developers/package
10 verbose request sending authorization for write operation
11 info attempt registry request try #1 at 11:45:23
12 verbose request using bearer token for auth
13 verbose request id 68630a0272c4946c
14 http request PUT https://registry.npmjs.org/-/team/tinkerpop/developers/package
15 http 403 https://registry.npmjs.org/-/team/tinkerpop/developers/package
16 verbose headers { 'content-type': 'application/json',
16 verbose headers   'cache-control': 'max-age=300',
16 verbose headers   'content-length': '21',
16 verbose headers   'accept-ranges': 'bytes',
16 verbose headers   date: 'Tue, 20 Feb 2018 10:45:24 GMT',
16 verbose headers   via: '1.1 varnish',
16 verbose headers   connection: 'keep-alive',
16 verbose headers   'x-served-by': 'cache-sjc3129-SJC',
16 verbose headers   'x-cache': 'MISS',
16 verbose headers   'x-cache-hits': '0',
16 verbose headers   'x-timer': 'S1519123524.466373,VS0,VE529',
16 verbose headers   vary: 'Accept-Encoding, Accept' }
17 verbose stack Error: Forbidden : -/team/tinkerpop/developers/package
17 verbose stack     at makeError (/Users/jorge/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:314:12)
17 verbose stack     at RegClient.<anonymous> (/Users/jorge/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:14)
17 verbose stack     at Request._callback (/Users/jorge/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
17 verbose stack     at Request.self.callback (/Users/jorge/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/request/request.js:186:22)
17 verbose stack     at emitTwo (events.js:126:13)
17 verbose stack     at Request.emit (events.js:214:7)
17 verbose stack     at Request.<anonymous> (/Users/jorge/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/request/request.js:1163:10)
17 verbose stack     at emitOne (events.js:116:13)
17 verbose stack     at Request.emit (events.js:211:7)
17 verbose stack     at IncomingMessage.<anonymous> (/Users/jorge/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/request/request.js:1085:12)
18 verbose statusCode 403
19 verbose cwd /Users/jorge/workspace/csharp-driver
20 verbose Darwin 16.6.0
21 verbose argv "/Users/jorge/.nvm/versions/node/v8.9.3/bin/node" "/Users/jorge/.nvm/versions/node/v8.9.3/bin/npm" "access" "grant" "read-write" "tinkerpop:developers" "gremlin"
22 verbose node v8.9.3
23 verbose npm  v5.5.1
24 error code E403
25 error Forbidden : -/team/tinkerpop/developers/package
26 verbose exit [ 1, true ]
```

cc @jbmusso

**Comment by jbmusso** [comment]
Confirming that I'm having this issue on my side with `npm access grant read-write tinkerpop:developers gremlin`

```
npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v9.5.0
npm info attempt registry request try #1 at 12:07:19
npm http request PUT https://registry.npmjs.org/-/team/tinkerpop/developers/package
npm http 403 https://registry.npmjs.org/-/team/tinkerpop/developers/package
npm ERR! code E403
npm ERR! Forbidden : -/team/tinkerpop/developers/package
```
Will happily provide more information if needed.

**Comment by soldair** [comment]
hey folks. please contact support@npmjs.com so we can make sure a ticket is created and you get help quickly.
