### ISSUE TITLE
NPM audit fails with 400 Bad Request - POST https://registry.npmjs.org/-/npm/v1/security/audits

### ISSUE THREAD

**Issue by c0debreaker** [npm/registry-issue-archive#320]
node 6.11.2
npm 6.0.1
MacOSX 10.12.6

Error in console
```
 ❯ npm audit
npm ERR! code E400
npm ERR! 400 Bad Request - POST https://registry.npmjs.org/-/npm/v1/security/audits

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rcamara/.npm/_logs/2018-05-14T14_49_02_111Z-debug.log
```

The 2018-05-14T14_49_02_111Z-debug.log log file
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/rcamara/.nvm/versions/node/v6.11.2/bin/node',
1 verbose cli   '/Users/rcamara/.nvm/versions/node/v6.11.2/bin/npm',
1 verbose cli   'audit' ]
2 info using npm@6.0.1
3 info using node@v6.11.2
4 verbose npm-session 0543347b23e71c28
5 timing audit compress Completed in 5ms
6 info audit Submitting payload of 14378 bytes
7 http fetch POST 400 https://registry.npmjs.org/-/npm/v1/security/audits 575ms
8 verbose stack Error: 400 Bad Request - POST https://registry.npmjs.org/-/npm/v1/security/audits
8 verbose stack     at res.buffer.catch.then.e (/Users/rcamara/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:94:15)
8 verbose stack     at process._tickCallback (internal/process/next_tick.js:109:7)
9 verbose statusCode 400
10 verbose cwd /Users/rcamara/repos/WebAppsProject/shared-deps
11 verbose Darwin 16.7.0
12 verbose argv "/Users/rcamara/.nvm/versions/node/v6.11.2/bin/node" "/Users/rcamara/.nvm/versions/node/v6.11.2/bin/npm" "audit"
13 verbose node v6.11.2
14 verbose npm  v6.0.1
15 error code E400
16 error 400 Bad Request - POST https://registry.npmjs.org/-/npm/v1/security/audits
17 verbose exit [ 1, true ]
```

**Comment by naugtur** [comment]
Same here, but installing npm 6.1.0 fixed it.

**Comment by alejandroiglesias** [comment]
6.1.0 didn't fix it for me.

**Comment by scottmtraver** [comment]
6.1.0 did not fix it for me either :(

**Comment by alejandroiglesias** [comment]
I can add that on 2 repositories it shows that error, but on a third one, it works fine. I don't know what the difference could be, other than the 2 repositories that fail have `private: true` on `package.json` (maybe not the only difference, but the only that comes to my mind now).

**Comment by batistafrancis** [comment]
Duplicated: https://github.com/npm/npm/issues/20604
