### ISSUE TITLE
Fastly error: unknown domain. 

### ISSUE THREAD

**Issue by omatrot** [npm/registry-issue-archive#338]
I'm unable to run `npm install` this morning in a react-native project.

Status report of the service is good.

Opening the following URL in a browser

https://registry.npmjs.org/react

led to this error:

Fastly error: unknown domain. Please check that this domain has been added to a service.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose npm-session d4289dbbc372dd20
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall VAPoc@0.0.1
7 info lifecycle VAPoc@0.0.1~preinstall: VAPoc@0.0.1
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 http fetch GET 500 https://registry.npmjs.org/react 70298ms attempt #3
15 silly fetchPackageMetaData error for react@^16.4.0 500 Internal Server Error: react@^16.4.0
16 http fetch GET 500 https://registry.npmjs.org/react-native 70295ms attempt #3
17 silly fetchPackageMetaData error for react-native@^0.55.4 500 Internal Server Error: react-native@^0.55.4
18 http fetch GET 500 https://registry.npmjs.org/react 70223ms attempt #3
19 http fetch GET 500 https://registry.npmjs.org/react-native 70222ms attempt #3
20 silly fetchPackageMetaData error for react@^16.4.0 500 Internal Server Error: react@^16.4.0
21 silly fetchPackageMetaData error for react-native@^0.55.4 500 Internal Server Error: react-native@^0.55.4

...
 verbose stack Error: 500 Internal Server Error: react@^16.4.0
23 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
23 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
23 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
23 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
23 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
23 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
23 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
23 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
23 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
23 verbose stack     at runCallback (timers.js:810:20)
23 verbose stack     at tryOnImmediate (timers.js:768:5)
23 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
24 verbose cwd /Users/omatrot/Projects/b2bot/vapoc
25 verbose Darwin 17.5.0
26 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
27 verbose node v8.11.2
28 verbose npm  v5.6.0
29 error code E500
30 error 500 Internal Server Error: react@^16.4.0
31 verbose exit [ 1, true ]
```

**Comment by omatrot** [comment]
It seems to be ISP related. I'm in France using SFR FTTH. Switched to my 4G Mobile ISP and the problem is gone.
