### ISSUE TITLE
Private module intermittently returning 404

### ISSUE THREAD

**Issue by alistairjcbrown** [npm/registry-issue-archive#362]
We're seeing private modules intermittently return 404 when being installed. User is successfully authenticated. Have been able to see this both on CI docker containers and locally.

eg.
```
23700 verbose stack Error: 404 Not Found: @shopkeep/generator-backoffice-react@https://registry.npmjs.org/@shopkeep/generator-backoffice-react/-/generator-backoffice-react-1.1.1.tgz
23700 verbose stack     at fetch.then.res (/Users/alistairbrown/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
23700 verbose stack     at tryCatcher (/Users/alistairbrown/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
23700 verbose stack     at Promise._settlePromiseFromHandler (/Users/alistairbrown/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
23700 verbose stack     at Promise._settlePromise (/Users/alistairbrown/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
23700 verbose stack     at Promise._settlePromise0 (/Users/alistairbrown/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
23700 verbose stack     at Promise._settlePromises (/Users/alistairbrown/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
23700 verbose stack     at Async._drainQueue (/Users/alistairbrown/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
23700 verbose stack     at Async._drainQueues (/Users/alistairbrown/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
23700 verbose stack     at Immediate.Async.drainQueues (/Users/alistairbrown/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
23700 verbose stack     at runCallback (timers.js:789:20)
23700 verbose stack     at tryOnImmediate (timers.js:751:5)
23700 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by alistairjcbrown** [comment]
Looks like this has also been reported by other people on twitter - https://twitter.com/ideabile/status/1011917834090409984

**Comment by arneke** [comment]
Same here, been problematic all day. Maybe it depends on the IP it resolves to, because it is either all or none.

**Comment by stevenuray** [comment]
Earnest has also been experiencing this issue for the past 16 hours. 

Our builds have failed over a dozen times in the past 24 hours because of this issue.

**Comment by chrisdickinson** [comment]
I am sorry for the trouble & delay. We've tracked down the bug and have rolled out a fix. This should be resolved now. Thank you!
