### ISSUE TITLE
npm ERR! code E400 bad request npm@latest

### ISSUE THREAD

**Issue by sandzOfTime** [npm/registry-issue-archive#368]
For whatever reason, cannot install any third party modules via the command line. My log file is the following:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'axios',
1 verbose cli   '--save' ]
2 info using npm@6.1.0
3 info using node@v10.5.0
4 verbose npm-session 2576bd2c4604ea83
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 400 https://registry.npmjs.org/axios 83ms
8 silly fetchPackageMetaData error for axios@latest 400 Bad Request: axios@latest
9 timing stage:rollbackFailedOptional Completed in 2ms
10 timing stage:runTopLevelLifecycles Completed in 349ms
11 verbose stack Error: 400 Bad Request: axios@latest
11 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
11 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
11 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
11 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
11 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
11 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose stack     at runCallback (timers.js:696:18)
11 verbose stack     at tryOnImmediate (timers.js:667:5)
11 verbose stack     at processImmediate (timers.js:649:5)
12 verbose cwd C:\Users\ats45\Documents\BahlocalScraper
13 verbose Windows_NT 10.0.17134
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "axios" "--save"
15 verbose node v10.5.0
16 verbose npm  v6.1.0
17 error code E400
18 error 400 Bad Request: axios@latest
19 verbose exit [ 1, true ]

Any help would be appreciated!

**Comment by sandzOfTime** [comment]
Found the issue. Had to reset my https-proxy to null using `npm config rm https-proxy`. Works fine now.
