### ISSUE TITLE
Can't publish new version of package. 

### ISSUE THREAD

**Issue by michelbitter** [npm/registry-issue-archive#385]
I've some problems with publishing my plugin [loghandler](https://www.npmjs.com/package/loghandler). Everytime when I do `npm publish` I get the following error:

```
32 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
33 info attempt registry request try #2 at 10:12:04
34 verbose request using bearer token for auth
33 info attempt registry request try #2 at 10:12:04
34 verbose request using bearer token for auth
35 http request PUT https://registry.npmjs.org/loghandler
36 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
37 info attempt registry request try #3 at 10:13:04
38 verbose request using bearer token for auth
39 http request PUT https://registry.npmjs.org/loghandler
40 error publish Failed PUT undefined
41 verbose stack Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
41 verbose stack     at errnoException (dns.js:50:10)
41 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
42 verbose cwd /Users/michelbitter/Development/projects/LogHandler
43 verbose Darwin 17.7.0
44 verbose argv "/Users/michelbitter/.nvm/versions/node/v8.11.3/bin/node" "/Users/michelbitter/.nvm/versions/node/v8.11.3/bin/npm" "publish"
45 verbose node v8.11.3
46 verbose npm  v6.2.0
47 error code ENOTFOUND
48 error errno ENOTFOUND
49 error syscall getaddrinfo
50 error network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
51 error network This is a problem related to network connectivity.
51 error network In most cases you are behind a proxy or have bad network settings.
51 error network
51 error network If you are behind a proxy, please make sure that the
51 error network 'proxy' config is set properly.  See: 'npm help config'
52 verbose exit [ 1, true ]
```

I tried it on two different internet connections with no effect. just to be clear I'm not behind any proxy so it looks like there are some troubles with connecting to registry of NPM. Maybe any downtime or problems with DNS resolvement?

**Comment by michelbitter** [comment]
Looks like several console applications give same problem. I'm sorry for making issue to soon!
